/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment4;


/**
 * This is the generated Hello World Greeting App.
 */
public class App {

  /**
   * Returns a nice greeting message.
   *
   * @return the greeing message.
   */
  public String getGreeting() {
    return "Hello World!";
  }

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    App theApp = new App();
    System.out.println(theApp.getGreeting());
    Member member1 = new Member("John Doe", "john.Doe@gmail.com");
    System.out.println(member1.getMemberID());
    Member member2 = new Member("John Doe", "john.Doe@gmail.com");
    System.out.println(member2.getMemberID());
    Member member3 = new Member("John Doe", "john.Doe@gmail.com");
    System.out.println(member3.getMemberID() + member3.getName() + member3.getEmail());

    }
}
