/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment4;

import assignment4.orderinheaven.Planet;
import assignment4.orderinheaven.Star;

/**
 * This is the generated Hello World Greeting App.
 */
public class App {

  /**
   * Returns a nice greeting message.
   *
   * @return the greeing message.
   */
  public String getGreeting() {
    return "Hello World!!";
  }

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    App theApp = new App();
    System.out.println(theApp.getGreeting());

        // Create a new star
        Star sun = new Star("Sun", 696340);

        // Add some planets
        sun.addPlanet("Earth", 6371, 149.6e6);
        sun.addPlanet("Mars", 3389, 227.9e6);

        // List planets
        for (Planet planet : sun.getPlanets()) {
            System.out.println(planet.getName());
        }

        // Delete a planet
        sun.deletePlanet("Earth");

        // List planets again
        System.out.println("After deletion:");
        for (Planet planet : sun.getPlanets()) {
            System.out.println(planet.getName());
        }
    }
}
